name: 'safestreets'
version: '1.0.0'

profile: 'safestreets'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  safestreets:
    +schema: raw

models:
  safestreets:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
